### ISSUE TITLE
typo in README.md

### ISSUE THREAD

**Issue by bassbone** [tkuchiki/alp#14]
I found a typo in README.md.

Download from https://github.com/tkuchiki/alp/releasse
-> Download from https://github.com/tkuchiki/alp/releases

**Comment by tkuchiki** [comment]
@bassbone Thank you so much!

**Comment by tkuchiki** [comment]
@bassbone Fixed!

**Comment by bassbone** [comment]
@tkuchiki Thanks! I confirmed the fix.
