### ISSUE TITLE
Suggestion to clarify dependencies

### ISSUE THREAD

**Issue by supermomonga** [tkuchiki/alp#3]
## Situation

I tried to build alp but got following error:

```
.go/src/github.com/tkuchiki/alp/main.go:572: undefined: parsetime.Parse
.go/src/github.com/tkuchiki/alp/main.go:589: undefined: parsetime.Parse
.go/src/github.com/tkuchiki/alp/main.go:625: undefined: parsetime.Log
```

I think the reason is that alp is not supporting latest `github.com/tkuchiki/parsetime` package.

## Problem

There is no information about supported version of dependency packages.

## Solution(Suggestion)

If you feel negative to use some dependency manager like Godep to make it easier to reproduce build dependencies, at least could you consider to clarify dependency information which includes supported version (or revision)?

**Comment by tkuchiki** [comment]
@supermomonga Thanks for reporting.

> I think the reason is that alp is not supporting latest github.com/tkuchiki/parsetime package.
Exactly.
I will release revised version.

>If you feel negative to use some dependency manager like Godep to make it easier to reproduce build dependencies, at least could you consider to clarify dependency information which includes supported version (or revision)?

I will support "vendoring".
Please wait a moment.

**Comment by supermomonga** [comment]
>I will support "vendoring".

Ah, I got it. I agree that this is the best way. I'm closing this issue.

**Comment by tkuchiki** [comment]
@supermomonga v0.2.4 released and support vendoring(use glide)!

**Comment by supermomonga** [comment]
Thanks 🎉
