### ISSUE TITLE
Can you also distribute ARM64 binaries?

### ISSUE THREAD

**Issue by catatsuy** [tkuchiki/alp#62]
Currently, you distribute AMD64 and MIPS binaries. I would like you to distribute ARM64 binaries.

Also, because it is difficult to handle zip files on Linux, I would like you to distribute them in gzip format if possible.

**Comment by tkuchiki** [comment]
Thank you for opening the issue.

OK, I will work on it!

**Comment by tkuchiki** [comment]
@catatsuy I'm sorry, for the late.
Please check [v1.0.9](https://github.com/tkuchiki/alp/releases/tag/v1.0.9) 🙏

**Comment by tkuchiki** [comment]
@catatsuy I think we can close this issue, so if you have any concerns, please re-open this issue!
